/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge05;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testsCC05(){
        LinkedList list1 = new LinkedList();
        System.out.println(list1);
        assertEquals("Challenge05.LinkedList@7f416310",list1.toString());
        list1.append(5);
        String str = list1.toString1();
        assertEquals(" { 5 } -> NULL",str);
        assertEquals(5, list1.head.value);
        list1.append(6);
        list1.append(7);
        String str1 = list1.toString1();
        assertEquals( " { 5 } -> { 6 } -> { 7 } -> NULL",str1);
        assertEquals(true,list1.includes(6));
        assertEquals(false,list1.includes(8));
        list1.append(9);
        String str2 = list1.toString1();
        assertEquals( " { 5 } -> { 6 } -> { 7 } -> { 9 } -> NULL",str2);
    }

    @Test void tests(){
        LinkedList list1 = new LinkedList();
        list1.append(1);
        list1.append(2);

        String str = list1.toString1();
//        System.out.println(str);
        assertEquals(" { 1 } -> { 2 } -> NULL",str);

        list1.append(5);
        list1.append(6);
        String str1 = list1.toString1();
//        System.out.println(str1);
        assertEquals(" { 1 } -> { 2 } -> { 5 } -> { 6 } -> NULL",str1);

        list1.insertBefore(5, 4);
        String str2 = list1.toString1();
//        System.out.println(str2);
        assertEquals(" { 1 } -> { 2 } -> { 4 } -> { 5 } -> { 6 } -> NULL",str2);

        list1.insertBefore(1, 0);
        String str3 = list1.toString1();
//        System.out.println(str3);
        assertEquals(" { 0 } -> { 1 } -> { 2 } -> { 4 } -> { 5 } -> { 6 } -> NULL",str3);

        list1.insertAfter(2, 3);
        String str4 = list1.toString1();
//        System.out.println(str4);
        assertEquals(" { 0 } -> { 1 } -> { 2 } -> { 3 } -> { 4 } -> { 5 } -> { 6 } -> NULL",str4);

        list1.insertAfter(6, 7);
        String str5 = list1.toString1();
//        System.out.println(str5);
        assertEquals(" { 0 } -> { 1 } -> { 2 } -> { 3 } -> { 4 } -> { 5 } -> { 6 } -> { 7 } -> NULL",str5);

    }

    @Test
    void challenge07test1(){
        LinkedList list = new LinkedList();
        list.append(5);
        list.append(3);
        list.append(1);
        list.append(9);

        int test1 = list.kthfromend(4);
        assertEquals(-1,test1);
    }

    @Test
    void challenge07test2(){
        LinkedList list = new LinkedList();
        list.append(5);
        list.append(3);
        list.append(1);
        list.append(9);

        int x = list.kthfromend(3);
        assertEquals(5,x);
    }

    @Test
    void challenge07test3(){
        LinkedList list = new LinkedList();
        list.append(5);
        list.append(3);
        list.append(1);
        list.append(9);

        int x = list.kthfromend(-1);
        assertEquals(-1,x);
    }

    @Test
    void challenge07test4(){
        LinkedList list = new LinkedList();
        list.append(5);

        int x = list.kthfromend(0);
        assertEquals(5,x);
    }

    @Test
    void challenge07test5(){
        LinkedList list = new LinkedList();
        list.append(5);
        list.append(3);
        list.append(1);
        list.append(9);

        int x = list.kthfromend(2);
        assertEquals(3,x);
    }
}
