/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge05;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void tests(){
        LinkedList list1 = new LinkedList();
        list1.append(1);
        list1.append(2);

        String str = list1.toString1();
        System.out.println(str);
        assertEquals(" { 1 } -> { 2 } -> NULL",str);

        list1.append(5);
        list1.append(6);
        String str1 = list1.toString1();
        System.out.println(str1);
        assertEquals(" { 1 } -> { 2 } -> { 5 } -> { 6 } -> NULL",str1);

        list1.insertBefore(5, 4);
        String str2 = list1.toString1();
        System.out.println(str2);
        assertEquals(" { 1 } -> { 2 } -> { 4 } -> { 5 } -> { 6 } -> NULL",str2);

        list1.insertBefore(1, 0);
        String str3 = list1.toString1();
        System.out.println(str3);
        assertEquals(" { 0 } -> { 1 } -> { 2 } -> { 4 } -> { 5 } -> { 6 } -> NULL",str3);

        list1.insertAfter(2, 3);
        String str4 = list1.toString1();
        System.out.println(str4);
        assertEquals(" { 0 } -> { 1 } -> { 2 } -> { 3 } -> { 4 } -> { 5 } -> { 6 } -> NULL",str4);

        list1.insertAfter(6, 7);
        String str5 = list1.toString1();
        System.out.println(str5);
        assertEquals(" { 0 } -> { 1 } -> { 2 } -> { 3 } -> { 4 } -> { 5 } -> { 6 } -> { 7 } -> NULL",str5);

    }
}
