/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge10;

public class Library {
    public static void main(String[] args) {
        Queue<Integer> queue = new Queue<>();
//        queue.enQueue(10);
//        queue.enQueue(20);
//        queue.enQueue(30);
//        queue.enQueue(40);

        queue.displayQueue();
        System.out.println("\n");
        queue.peek();
//        System.out.println(queue.deQueue());
//        queue.displayQueue();
    }
}
