/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Challenge10;

public class Library {
    public static void main(String[] args) {
        Queue<Integer> queue = new Queue<>();
//        queue.enQueue(10);
//        queue.enQueue(20);
//        queue.enQueue(30);
//        queue.enQueue(40);

        queue.displayQueue();
        System.out.println("\n");
        queue.peek();
//        System.out.println(queue.deQueue());
//        queue.displayQueue();

        PseudoQueue<Integer> q1 = new PseudoQueue<>();
        q1.enQueue(1);
        q1.enQueue(2);
        q1.enQueue(3);
        q1.enQueue(4);

        q1.stack1.displayStack();
        System.out.println("\n");

        q1.deQueue();
        q1.stack1.displayStack();
        System.out.println("\n");





    }
}
