/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.Test;

import java.util.Set;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void graphCC35(){
        Graph<Integer> graphObject = new Graph<>();
        Node<Integer> Node1 = new Node<>(1);
        Node<Integer> Node2 = new Node<>(2);
        Node<Integer> Node3 = new Node<>(3);
        graphObject.addNode(Node1);
        graphObject.addNode(Node2);
        graphObject.addNode(Node3);
        graphObject.addEdge(Node1, Node2);
        graphObject.addEdge(Node1, Node3);
        graphObject.addEdge(Node2, Node3);
        graphObject.addEdge(Node3, Node1);

        assertEquals(java.util.Optional.of(1), java.util.Optional.ofNullable(graphObject.addNode(Node1)));

        Set<Node<Integer>> nodes = graphObject.getNodes();
        for(Node<Integer> key: nodes){
            System.out.println(key.getVertex());
        }
        
    }
}
